# HomeKB engine — standalone binary (docs/ARCHITECTURE.md "Distribution").
# GENERATED by the engine-release workflow (publish-channels) — do not
# hand-edit; the next release overwrites this file.
class Homekb < Formula
  desc "Personal markdown knowledge base: compile, semantic search, serve"
  homepage "https://github.com/do-md/homekb"
  version "0.2.0"

  on_macos do
    on_arm do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.2.0/homekb-macos-arm64.tar.gz"
      sha256 "3972b02a227a0d6029d16ec66e7240a27704b207d1846e6af813b896b28361f9"
    end
    on_intel do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.2.0/homekb-macos-x64.tar.gz"
      sha256 "1996494366848beccd10ad2af86018946f1d469698c59dc53ecc2ca982e2bd8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.2.0/homekb-linux-x64.tar.gz"
      sha256 "b7cfdee74a816ae7ca0e0cf286f7fba0615fab7e61007722382cdc3de07c9b6c"
    end
  end

  def install
    bin.install "homekb"
  end

  test do
    assert_match "homekb #{version}", shell_output("#{bin}/homekb --version")
  end
end
