# HomeKB engine — standalone binary (docs/ARCHITECTURE.md "Distribution").
# GENERATED by the engine-release workflow (publish-channels) — do not
# hand-edit; the next release overwrites this file.
class Homekb < Formula
  desc "Personal markdown knowledge base: compile, semantic search, serve"
  homepage "https://github.com/do-md/homekb"
  version "0.3.3"

  on_macos do
    on_arm do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.3.3/homekb-macos-arm64.tar.gz"
      sha256 "324b431ced1561212b58acb8e476ba270cf8d0d64e6ce36cdda3716bf23fbf24"
    end
    on_intel do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.3.3/homekb-macos-x64.tar.gz"
      sha256 "a5000f2bca37979ee399d6ccde87d7fc3f44c37d24b3c723f19e6837ce78f5a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.3.3/homekb-linux-x64.tar.gz"
      sha256 "daff34b752a4891144ef42d919a2ec09c93fd5f2d71ed2e34eaf8ead5d446961"
    end
  end

  def install
    bin.install "homekb"
  end

  test do
    assert_match "homekb #{version}", shell_output("#{bin}/homekb --version")
  end
end
