# HomeKB engine — standalone binary (docs/ARCHITECTURE.md "Distribution").
# GENERATED by the engine-release workflow (publish-channels) — do not
# hand-edit; the next release overwrites this file.
class Homekb < Formula
  desc "Personal markdown knowledge base: compile, semantic search, serve"
  homepage "https://github.com/do-md/homekb"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.3.0/homekb-macos-arm64.tar.gz"
      sha256 "ce4c51e152d29bb3d608dfae7987d8c6888a490db827a0af641e5a7a4e0f294b"
    end
    on_intel do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.3.0/homekb-macos-x64.tar.gz"
      sha256 "90c9b8db6fa4f1c934a45cd3453af5fa631e5272a3e26e3b4d8c424d6b62c33f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/do-md/homekb/releases/download/engine-v0.3.0/homekb-linux-x64.tar.gz"
      sha256 "def7cfd642ccb0b8b85b153d6aa751b1a1c7e282c491e646b19cca0d713faba2"
    end
  end

  def install
    bin.install "homekb"
  end

  test do
    assert_match "homekb #{version}", shell_output("#{bin}/homekb --version")
  end
end
